AWSTemplateFormatVersion: 2010-09-09
Description: Jathurchan Selvakumar - Template to create a VPC
Resources:
  UdacityVPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      Tags:
      - Key: name
        Value: myfirsttestvpc